openapi: 3.0.0
info:
  title: OCPP Device Service
  description: ""
  termsOfService: ""
  contact:
    email: gr.szalay@gmail.com
  version: v1.0.0
servers:
- url: https://virtserver.swaggerhub.com/gregszalay/ocpp_device_service/v1.0.0
  description: SwaggerHub API Auto Mocking
- url: /
tags:
- name: Get Charger
  description: Get a single charger in the database.
- name: List Chargers
  description: List all chargers in the database.
- name: Create Charger
  description: Create a charger in the database.
- name: Update Charger
  description: Update a charger in the database.
- name: Delete Charger
  description: Delete a charger in the database.
paths:
  /charger/{chargerId}:
    get:
      tags:
      - Get Charger
      summary: Gets device data based on device id
      description: Get device data
      operationId: findChargers
      parameters:
      - name: chargerId
        in: path
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/ChargerID'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charger'
        "400":
          description: Invalid status value
  /list:
    get:
      tags:
      - List Chargers
      summary: Get array of all devices
      description: Get device data
      operationId: findAllChargers
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargerArray'
        "400":
          description: Invalid status value
  /create:
    post:
      tags:
      - Create Charger
      summary: Adds a new charger in db
      operationId: createNewCharger
      requestBody:
        description: Creates a new device
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Charger'
        required: true
      responses:
        "200":
          description: Successful registration of new device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargerID'
        "400":
          description: Unsuccessful creation
  /update/{chargerId}:
    post:
      tags:
      - Update Charger
      summary: Updates a charger in db
      operationId: updateCharger
      parameters:
      - name: chargerId
        in: path
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/ChargerID'
      requestBody:
        description: Updates device
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Charger'
        required: true
      responses:
        "200":
          description: Successful registration of new device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargerID'
        "400":
          description: Unsuccessful morgage payment calculation
  /delete/{chargerId}:
    post:
      tags:
      - Delete Charger
      summary: Deletes a charger in db
      operationId: deleteCharger
      parameters:
      - name: chargerId
        in: path
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/ChargerID'
      responses:
        "200":
          description: Successful deletion of device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charger'
        "400":
          description: Unsuccessful deletion
components:
  schemas:
    Charger:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ChargerID'
        serialNumber:
          type: string
          description: OCPP - Optional. Vendor-specific device identifier.
          example: "24"
        model:
          type: string
          description: OCPP - Required. Defines the model of the device.
          example: GT-5000
        vendorName:
          type: string
          description: OCPP - Required. Identifies the vendor (not necessarily in
            a unique manner).
          example: ChargerMaker Inc.
        firmwareVersion:
          type: string
          description: OCPP - Optional. This contains the firmware version of the
            Charging Station.
          example: "2.8"
        modem:
          $ref: '#/components/schemas/Charger_modem'
        location:
          $ref: '#/components/schemas/Charger_location'
        lastBoot:
          type: string
          description: Date and time of last BootNotification received. As defined
            by date-time - RFC3339
          format: date-time
      example:
        serialNumber: "24"
        lastBoot: 2000-01-23T04:56:07.000+00:00
        modem:
          iccid: "24"
          imsi: "24"
        model: GT-5000
        location:
          lng: -71.1854651
          lat: 42.366446
        id: 0
        vendorName: ChargerMaker Inc.
        firmwareVersion: "2.8"
    ChargerArray:
      type: array
      items:
        $ref: '#/components/schemas/Charger'
      x-schema-name: ChargerArray
    ChargerID:
      type: integer
    Charger_modem:
      type: object
      properties:
        iccid:
          type: string
          description: OCPP - Optional. This contains the ICCID of the modem’s SIMcard.
          example: "24"
        imsi:
          type: string
          description: OCPP - Optional. This contains the IMSI of the modem’s SIM
            card.
          example: "24"
      example:
        iccid: "24"
        imsi: "24"
    Charger_location:
      type: object
      properties:
        lat:
          type: number
          example: 42.366446
        lng:
          type: number
          example: -71.1854651
      example:
        lng: -71.1854651
        lat: 42.366446
